services:
  backend:
    build: backend/.
    container_name: backend
    depends_on:
      - database
    env_file:
      - ./backend/.env
    volumes:
      - ./app/config:/app/config  # Mount only specific subdirectories
      - ./app/logs:/app/logs
    ports:
      - "8080:8080"
    networks:
      - msev

  database:
    container_name: database
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - backend/.env
    networks:
      - msev

  frontend:
    container_name: frontend
    build: frontend/.
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - msev

  reverse-proxy:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"  # For HTTPS if needed in the future
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - msev
networks:
  msev:
    driver: bridge