services:
  backend:
    build: backend/.
    container_name: backend
    depends_on:
      - database
    env_file:
      - ./backend/.env
    networks:
      - msev

  database:
    container_name: database
    image: postgres
    env_file:
      - backend/.env
    networks:
      - msev

  frontend:
    container_name: frontend
    build: frontend/.
    depends_on:
      - backend
    networks:
      - msev

  reverse-proxy:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"  # For HTTPS if needed in the future
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - msev
networks:
  msev:
    driver: bridge