services:
  backend:
    build: backend/.
    container_name: backend
    depends_on:
      - database
    env_file:
      - ./backend/.env
    networks:
      - msev
  

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yaml

    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml
    networks:
      - msev

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./config/grafana:/etc/grafana/provisioning/
    networks:
      - msev



  database:
    container_name: database
    image: postgres
    env_file:
      - backend/.env
    networks:
      - msev
    volumes:
      - ./postgres/:/var/lib/postgresql/data

  frontend:
    container_name: frontend
    env_file:
      - frontend/.env
    environment:
      - VITE_BACKEND_URL=http://localhost/api/v1
    build: frontend/.
    depends_on:
      - backend
    networks:
      - msev

  reverse-proxy:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - msev
networks:
  msev:
    driver: bridge
