services:
  backend:
    build: backend/.
    container_name: backend
    depends_on:
      - database
    env_file:
      - ./backend/.env
    volumes:
      - ./app/config:/app/config  # Mount only specific subdirectories
      - ./app/logs:/app/logs
    ports:
      - "8080:8080"
    networks:
      - msev

  database:
    container_name: database
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - backend/.env
    networks:
      - msev

networks:
  msev:
    driver: bridge