services:
  backend:
    build: backend/.
    container_name: backend
    depends_on:
      - database
    env_file:
      - ./backend/.env
    networks:
      - msev

  database:
    container_name: database
    image: postgres
    env_file:
      - backend/.env
    networks:
      - msev

  frontend:
    build: .
    container_name: nginx_frontend
    networks:
      - msev
    ports:
      - "443:443"
    depends_on:
      - backend
    env_file:
      - .env

networks:
  msev:
    driver: bridge
