on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: self-hosted 
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      # prepare the certificates on the server in advance
      - name: Git pull      
        run: |
          echo "${{ secrets.SSH_VM_PRIVATE_KEY }}" > key
          chmod 600 key
          ssh -o StrictHostKeyChecking=no -i key hfreitas@deti-tqs-22.ua.pt << 'EOF'
          rm key
          cd MSEV-TQS 
          docker compose down
          git restore .
          git checkout main
          git pull origin main
          chmod +x deploy.sh
          ./deploy.sh
          EOF



