on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: self-hosted 
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_VM_PRIVATE_KEY }}

      # prepare the certificates on the server in advance
      - name: Git pull      
        run: |
              ssh -o StrictHostKeyChecking=no hfreitas@deti-tqs-22.ua.pt << 'EOF'
              cd MSEV-TQS 
              docker compose down
              git restore .
              git checkout main
              git pull origin main
              chmod +x deploy.sh
              ./deploy.sh
              EOF



