name: Spring Boot CI

on:
  pull_request:
    branches:
      - dev
      - main
    paths:
      - '**/backend/**'  # Only triggers if files in the backend directory are changed

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner for Maven build
    
    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Java (adjust the Java version as per your project requirements)
    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'  # Adjust the Java version based on your project's needs
    
    # Step 3: Install dependencies and run tests for Spring Boot (using Maven)
    - name: Install dependencies and test Spring Boot project
      working-directory: ./backend  # Change this to where your Spring Boot project is located
      run: |
        mvn clean install  # This will clean and install dependencies and run tests

    # Step 4: Build the Spring Boot application
    - name: Build Spring Boot application
      working-directory: ./backend  # Change this to where your Spring Boot project is located
      run: |
        mvn package  # This will build the project and create a deployable .jar file

