name: Spring Boot CI

on:
  pull_request:
    branches:
      - dev
      - main
    paths:
      - '**/backend/**'  

jobs:
  build:
    runs-on: ubuntu-latest  

    env:
      GEOCODING_APIKEY: ${{ secrets.GEOCODING_APIKEY }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java 17
      uses: actions/setup-java@v2
      with:
        java-version: '17' 
        distribution: "temurin"    
    - name: Install dependencies and test Spring Boot project

      working-directory: ./backend  
      run: |
        mvn clean install  
    - name: Build Spring Boot application
      working-directory: ./backend  
      run: |
        mvn package  

